version: '3.8'

services:
  zookeeper-brokerage:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-brokerage
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka-network
  kafka-brokerage:
      image: confluentinc/cp-kafka:latest
      container_name: kafka-brokerage
      depends_on:
        - zookeeper-brokerage
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper-brokerage:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-brokerage:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      networks:
        - kafka-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-brokerage:9092
    depends_on:
      - kafka-brokerage
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
